CREATE DATABASE IF NOT EXISTS `restoran`;

USE `restoran`;

CREATE TABLE kategorijeJela (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    naziv VARCHAR(255) NOT NULL
);

CREATE TABLE jela (
    id INT UNSIGNED AUTO_INCREMENT,
    naziv VARCHAR(255) NOT NULL,
    kategorijaId INT UNSIGNED NOT NULL,
    PRIMARY KEY (id),
    FOREIGN KEY (kategorijaId) REFERENCES kategorijeJela(id) ON DELETE CASCADE
);

CREATE TABLE konobari (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    ime VARCHAR(255) NOT NULL,
    prezime VARCHAR(255) NOT NULL,
    spol CHAR(1) NOT NULL CHECK (spol IN ('M', 'Z'))
);

CREATE TABLE stolovi (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    broj INT UNSIGNED NOT NULL CHECK (broj BETWEEN 1 AND 100)
);

CREATE TABLE narudzbe (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    jeloId INT UNSIGNED NOT NULL,
    konobarId INT UNSIGNED NOT NULL,
    stolId INT UNSIGNED NOT NULL,
    datum DATE NOT NULL,
    FOREIGN KEY (jeloId) REFERENCES jela(id) ON DELETE CASCADE,
    FOREIGN KEY (konobarId) REFERENCES konobari(id) ON DELETE CASCADE,
    FOREIGN KEY (stolId) REFERENCES stolovi(id) ON DELETE CASCADE
);